---
name: MusicBrainz-DiscID
version: 0.03
author:
  - 'Nicholas J. Humfrey <njh@aelius.com>'
abstract: Perl interface for the MusicBrainz libdiscid library
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
requires:
  Test: 1.00
  Test::More: 0
build_requires:
  Module::Build: 0.20
recommends:
  Test::Pod: 1.00
provides:
  MusicBrainz::DiscID:
    file: lib/MusicBrainz/DiscID.pm
    version: 0.03
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
