---
abstract: 'Perl interface for the MusicBrainz libdiscid library'
author:
  - 'Nicholas J. Humfrey'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MusicBrainz-DiscID
no_index:
  directory:
    - t
    - inc
resources:
  bugtracker: https://github.com/njh/perl-musicbrainz-discid/issues
  repository: https://github.com/njh/perl-musicbrainz-discid.git
version: 0.04
